[workspace]
members = [ "rtc_tenclave", "rtc_uenclave", "rtc_types", "rtc_data_enclave", "rtc_data_service"] 

[patch."https://github.com/apache/teaclave-sgx-sdk.git"]
sgx_types = { git = "https://github.com/registreerocks/incubator-teaclave-sgx-sdk.git", branch = "impl-derive-traits-sgx_types" }
sgx_tcrypto = { git = "https://github.com/registreerocks/incubator-teaclave-sgx-sdk.git", branch = "impl-derive-traits-sgx_types" }