[package]
name = "rtc_app_backend"
version = "0.1.0"
authors = ["Registree"]
edition = "2018"

[dependencies]
actix-web = "3"
serde = { version = "1.0.125", features = ["derive"] }
dotenv = "0.15.0"
config = "0.11.0"
